import React, { useState } from 'react'
import { Search, FileText } from 'lucide-react'
import { PageTransition, SuccessCelebration } from '../animations/AnimationPrimitives'
import { AnimatedMicroscopeSVG } from '../svg/AnimatedSVGs'
import { gameAudio } from '../../../utils/gameAudio'
import { gamification } from '../../../utils/gamification'
import type { ExperienceComponentProps } from './ExplorationExperience'

// ─── 9. INVESTIGATION EXPERIENCE ─────────────────────────────────────────────
// Structure: Cyber Forensic Audit Station, metadata inspector, deepfake artifact detector, and verdict stamp
export const InvestigationExperience: React.FC<ExperienceComponentProps> = ({
  topicTitle,
  canonicalSection,
  config,
  isCompleted,
  onComplete,
}) => {
  const [analyzedItems, setAnalyzedItems] = useState<number[]>([])
  const [stampVerified, setStampVerified] = useState(false)

  const auditSamples = config?.auditSamples || [
    {
      id: 0,
      title: 'Digital Watermark & C2PA Provenance',
      finding: 'Cryptographic header confirms content was generated by an authorized generative model.',
      status: 'Verified Authenticated',
      badgeColor: 'emerald',
    },
    {
      id: 1,
      title: 'Pupil Reflection & Spectral Frequency',
      finding: 'Irregular specular glare patterns detected on subject eyes, indicating synthetic pixel synthesis.',
      status: 'Synthetic Artifact Flagged',
      badgeColor: 'rose',
    },
    {
      id: 2,
      title: 'Phoneme-Lip Synchronization Audit',
      finding: 'Audio phonemes lead mouth movements by 180 milliseconds—classic symptom of dubbing deepfakes.',
      status: 'Temporal Discrepancy Found',
      badgeColor: 'amber',
    },
  ]

  const handleInspect = (idx: number) => {
    gameAudio.playTap()
    if (!analyzedItems.includes(idx)) {
      const next = [...analyzedItems, idx]
      setAnalyzedItems(next)
      if (next.length === auditSamples.length) {
        gameAudio.playSuccess()
      }
    }
  }

  const handleVerifyReport = () => {
    gameAudio.playSuccess()
    setStampVerified(true)
    gamification.launchConfetti()
    if (!isCompleted) onComplete()
  }

  const allAnalyzed = analyzedItems.length === auditSamples.length

  return (
    <PageTransition className="p-4 sm:p-8 max-w-5xl mx-auto space-y-8">
      {/* Investigation Header */}
      <div className="flex items-center justify-between p-6 rounded-3xl bg-slate-900/90 border-2 border-indigo-500/30">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-indigo-500/20 text-indigo-300 border border-indigo-400/40 flex items-center justify-center">
            <Search size={24} />
          </div>
          <div>
            <span className="text-xs font-bold text-indigo-400 uppercase tracking-widest">Digital Forensics Laboratory</span>
            <h1 className="text-xl sm:text-2xl font-black text-white">{topicTitle}</h1>
          </div>
        </div>
        <div className="text-xs font-bold text-slate-300 bg-slate-800 px-3 py-1.5 rounded-full border border-slate-700">
          Audited: {analyzedItems.length} / {auditSamples.length}
        </div>
      </div>

      {/* Forensic Audit Desk */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
        <div className="lg:col-span-4 p-6 rounded-3xl bg-slate-950/80 border-2 border-indigo-500/30 flex flex-col items-center justify-center text-center">
          <AnimatedMicroscopeSVG size={140} className="mb-4" />
          <h3 className="font-bold text-white text-base">Spectral Anomaly Lens</h3>
          <p className="text-xs text-slate-400 mt-1 leading-relaxed">
            Audit high-frequency pixel anomalies and metadata provenance to verify truth.
          </p>
        </div>

        <div className="lg:col-span-8 space-y-3">
          {auditSamples.map((sample: any, idx: number) => {
            const isDone = analyzedItems.includes(idx)
            return (
              <div
                key={sample.id}
                onClick={() => handleInspect(idx)}
                className={`p-5 rounded-2xl border-2 cursor-pointer transition-all ${
                  isDone
                    ? 'bg-slate-900 border-indigo-500/50 shadow-md'
                    : 'bg-slate-900/40 border-slate-800 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-bold text-sm text-white flex items-center gap-2">
                    <FileText size={16} className="text-indigo-400" /> {sample.title}
                  </h4>
                  {isDone && (
                    <span className={`text-[11px] font-bold px-2.5 py-0.5 rounded-full bg-${sample.badgeColor}-500/20 text-${sample.badgeColor}-300 border border-${sample.badgeColor}-500/30`}>
                      {sample.status}
                    </span>
                  )}
                </div>
                <p className="text-xs text-slate-300 leading-relaxed">{sample.finding}</p>
              </div>
            )
          })}
        </div>
      </div>

      {/* Report Validation Stamp */}
      <div className="p-6 rounded-3xl bg-slate-900/90 border-2 border-indigo-500/30 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <h4 className="font-bold text-white text-sm">Official Forensic Audit Certification</h4>
          <p className="text-xs text-slate-400">Complete all sample scans above to sign and publish the audit.</p>
        </div>
        <button
          disabled={!allAnalyzed || stampVerified}
          onClick={handleVerifyReport}
          className="px-8 py-3 rounded-2xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 disabled:opacity-40 text-white font-bold text-sm shadow-md"
        >
          {stampVerified ? '✓ Audit Signed & Sealed' : 'Stamp Forensic Seal →'}
        </button>
      </div>

      {stampVerified && (
        <SuccessCelebration
          title="🎉 Forensic Investigation Verified!"
          subtitle={`You successfully isolated deepfake signals and certified the integrity of ${topicTitle}.`}
          xpEarned={canonicalSection.xpReward || 25}
        />
      )}
    </PageTransition>
  )
}
